disabled_rules:
  - file_length
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests/ParseSwiftTests/ParseEncoderTests
  - DerivedData
  - .build
  - .dependencies
