disabled_rules:
  - large_tuple
  - unused_optional_binding
  - type_name
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests/ParseSwiftTests/ParseEncoderTests
  - DerivedData
  - .build
  - .dependencies
