disabled_rules:
  - file_length
  - identifier_name
  - blanket_disable_command
  - non_optional_string_data_conversion
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests/ParseSwiftTests/ParseEncoderTests
  - DerivedData
  - .build
  - .dependencies
