#!/bin/bash

# Prepare podspec update
TEMPLATE_FILE_NAME="ParseSwiftOG.podtemplate"
OUT_FILE_NAME="ParseSwiftOG.podspec"

# Load the template podspec and replace version
TEMPLATE=$(cat "$TEMPLATE_FILE_NAME" | sed "s/\[\[VERSION\]\]/${BUILD_VERSION}/g")

echo "$TEMPLATE" > "$OUT_FILE_NAME"
