name: release
on:
  release:
    types: [published]
env:
  CI_XCODE_14: '/Applications/Xcode_14.3.1.app/Contents/Developer'
  CI_XCODE_LATEST: '/Applications/Xcode_15.4.app/Contents/Developer'

jobs:
  cocoapods:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Update Framework Version
        run: ./Scripts/update_build
        env:
          BUILD_VERSION: ${{ env.TAG }}
      - name: Deploy CocoaPods
        run: set -o pipefail && env NSUnbufferedIO=YES pod trunk push ParseSwiftOG.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          DEVELOPER_DIR: ${{ env.CI_XCODE_LATEST }}

  docs:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build and Deploy Docs
        run: set -o pipefail && env NSUnbufferedIO=YES Scripts/update-gh-pages-documentation-site
        env:
          CURRENT_BRANCH_NAME: release
          DEVELOPER_DIR: ${{ env.CI_XCODE_LATEST }}
