//
//  ParsePushApplePayload.swift
//  ParseSwift
//
//  Created by Corey Baker on 9/16/24.
//  Copyright © 2024 Network Reconnaissance Lab. All rights reserved.
//

import Foundation

// swiftlint:disable line_length

protocol ParsePushAppleHeader {

    /**
     The unique ID for the notification.
     */
    var id: UUID? { get set }
    /**
     The unique ID for this request.
     - note: Used for broadcast push notifications.
     */
    var requestId: UUID? { get set }
    /**
     A base64-encoded string that identifies the channel to publish the payload.
     The channel ID is generated by sending channel creation request to APNs.
     - note: Used for broadcast push notifications.
     */
    var channelId: String? { get set }
    /**
     Multiple notifications with same collapse identifier are displayed to the user as a single
     notification. The value should not exceed 64 bytes.
     */
    var collapseId: String? { get set }
    /**
     The priority of the notification. Specify 10 to send the notification immediately.
     Specify 5 to send the notification based on power considerations on the user’s device.
     See Apple's [documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns)
     for more information.
     - warning: For Apple OS's only.
     */
    var priority: Int? { get set }
    /**
     The destination topic for the notification.
     */
    var topic: String? { get set }
    /**
     The type of the notification. The value is alert or background. Specify alert when the
     delivery of your notification displays an alert, plays a sound, or badges your app’s icon.
     Specify background for silent notifications that do not interact with the user.
     Defaults to alert if no value is set.
     - warning: Required when delivering notifications to
     devices running iOS 13 and later, or watchOS 6 and later. Ignored on earlier OS versions.
     */
    var pushType: ParsePushPayloadApple.PushType? { get set }
}

public protocol ParsePushApplePayload: ParsePushApplePayloadable {
    /**
     The background notification flag. If you are a writing an app using the Remote Notification
     Background Mode introduced in iOS7 (a.k.a. “Background Push”), set this value to
     1 to trigger a background update. For more informaiton, see [Apple's documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).
     - warning: For Apple OS's only. You also have to set `pushType` starting iOS 13
     and watchOS 6.
     */
    var contentAvailable: Int? { get set }
    /**
     The notification service app extension flag. Set this value to 1 to trigger the system to pass the notification to your notification service app extension before delivery. Use your extension to modify the notification’s content. For more informaiton, see [Apple's documentation](https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications).
     - warning: You also have to set `pushType` starting iOS 13
     and watchOS 6.
     */
    var mutableContent: Int? { get set }
}
